
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class Attractor : MonoBehaviour
{
    public LayerMask AttractionLayer;
    public float gravity=10;
    [SerializeField] private float Radius=10;
    public List<Collider2D> AttractedObjects=new List<Collider2D>();
    [HideInInspector] public Transform attractorTransform;

    void Awake()
    {
        attractorTransform=GetComponent<Transform>();
    }
    // Start is called before the first frame update
    void Update()
    {
        SetAttractedObjects();
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        AttractObjects();
    }

    void SetAttractedObjects()
    {
        AttractedObjects=Physics2D.OverlapCircleAll(attractorTransform.position,Radius,AttractionLayer).ToList();
    }

    void AttractObjects() 
    {
        for(int i=0;i<AttractedObjects.Count;i++)
        {
            AttractedObjects[i].GetComponent<Attractable>().Attract(this);
        }
    }
    void OnDrawGizmosSelected()
    {
        Gizmos.color=Color.magenta;
        Gizmos.DrawWireSphere(transform.position,Radius);
    }
}
